In [16]:
def getAngleRange(origin, point):
    """
    Description:
    Each point gets an angle range. 
    Closer points take up a larger range of angles,
    further points take up a smaller range of angles.

    Implementation:
    s = distance from the middle of each pixel
    a = angle between the two pixels can then be calculated using atan2
    b = asin( (sqrt(2)/2) / s )
    minangle = a - b
    maxangle = a + b
    """
    origin_mp = Point(point.x - 0.5, point.y - 0.5)
    point_mp = Point(origin.x - 0.5, origin.y - 0.5)
    s = dist(origin_mp.raw(), point_mp.raw())
    print(f"s = {s}")
    a = atan2(point_mp.y - origin_mp.y, point_mp.x - origin_mp.x)
    print(f"a = {a}")

    b = asin(sqrt(2)/2 / s)
    print(f"b = {b}")

    minangle = a - b
    maxangle = a + b
    return minangle, maxangle

In [1]:
from math import asin, atan2, dist, sqrt

In [2]:
class Point:
    """
    Point with natural number coordinates,
    either a point in the world, or on the screen (scaled up world).
    """
    def __init__(self, x, y, worldpoint=True):
        self.x = x
        self.y = y
        self.worldpoint = worldpoint  # boolean value

    def raw(self):
        return (self.x, self.y)

    def scale(self, scalar):  
        # scaling changes worldpoint->screenpoint or screenpoint->worldpoint
        return Point(self.x * scalar, self.y * scalar, not self.worldpoint)

    def __eq__(self, other):
        if isinstance(other, Point):
            return self.x == other.x and self.y == other.y and self.worldpoint == other.worldpoint
        return False

    def __hash__(self):
        return hash(self.raw())

    def __str__(self):
        return f"x = {self.x}, y = {self.y}"
    
    def getScreenpoint(self):
        if self.worldpoint:
            return self.scale(SCREENSIZE / WORLDSIZE)
        else:
            raise RuntimeError("Point is already screenpoint")
    
    def getWorldPt(self):
        if not self.worldpoint:
            return self.scale(WORLDSIZE / SCREENSIZE)
        else:
            raise RuntimeError("Point is already worldpoint")
    
    def draw(self, color):
        if self.worldpoint:
            raise RuntimeError("Cannot draw worldpoint")
        else:
            scalar = SCREENSIZE / WORLDSIZE
            pygame.draw.rect(SCREEN, color, (round(self.x), round(self.y), scalar, scalar))

In [3]:
WORLDSIZE = 100
SCREENSIZE = 600  # should be a multiple of WORLDSIZE

In [6]:
getAngleRange(Point(0, 0), Point(0, 4))

(-1.7485069276400083, -1.3930857259497849)

In [7]:
getAngleRange(Point(0, 0), Point(0, 1))

(-2.356194490192345, -0.7853981633974482)

In [8]:
getAngleRange(Point(0, 0), Point(0, 100))

(-1.577867453533653, -1.5637252000561401)

In [9]:
180 / pi 


NameError: name 'pi' is not defined

In [10]:
from math import pi

In [11]:
180 / pi 

57.29577951308232

In [12]:
360 * pi / 180

6.283185307179586

In [13]:
90 * pi / 180

1.5707963267948966

In [18]:
getAngleRange(Point(0, 0), Point(5, 0))

s = 5.0
a = 3.141592653589793
b = 0.1418970546041639


(2.999695598985629, 3.283489708193957)

In [15]:
atan2(0, 1)

0.0

In [19]:
a=  []

In [20]:
a.append((1, 2))

In [21]:
a

[(1, 2)]

In [22]:
def foo():
    return 1, 2
    

In [23]:
a.append(foo())

In [24]:
a

[(1, 2), (1, 2)]

In [27]:
import numpy

In [44]:
a = numpy.array([1, 2])

In [35]:
b = numpy.array([3, 4])

In [36]:
a + b

array([4, 6])

In [40]:
sum(a, b)

array([6, 7])

In [43]:
a

array([1, 2])

In [45]:
b

array([3, 4])